database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "postgres"
  name: "postgres"
  sslmode: "disable"

migrations:
  path: "database/migrations"

server:
  port: 52281
  timeout: 30s