server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: .properties
  cassandra:
    keyspace-name: ${DEVICE_KEYSPACE_NAME}
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT}
    schema-action: ${CASSANDRA_SCHEMA_ACTION}
    model-path: ${CASSANDRA_MODEL_PATH}

kafka:
  server: ${KAFKA_SERVER}

schema:
  registry:
    url: ${SCHEMA_REGISTRY_URL}

consumer:
  event:
    topic: ${EVENT_TOPIC}
    groupId: ${EVENT_GROUP_ID}
    concurrency: ${EVENT_CONCURRENCY}

producer:
  deviceId:
    topic: ${DEVICE_ID_TOPIC}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_INCLUDE}
  endpoint:
    health:
      show-details: ${MANAGEMENT_SHOW_DETAILS}
